baseURL = "https://hugo-store.vercel.app/"
languageCode = "en-us"
title = "Ismir Peregrine Dossiers"
theme = "PaperMod"

[pagination]
  pagerSize = 5

enableRobotsTXT = true

[params]
  env = "production"
  defaultTheme = "dark"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = false
  displayFullLangName = true
  useHLJS = true
  hideFooter = false
  author = "Guiness"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "vault"
    name = "Vault"
    url = "https://quartz-vault.vercel.app/"
    weight = 2
